### ISSUE TITLE
./dns-update.sh: line 87: mail: command not found

### ISSUE THREAD

**Issue by jjuk2023** [Steve8291/dns-update-cloudflare#1]
Hi there, when trying to run the script I get the following error. This is on a bitnami wordpress image on AWS. If I need to install any other packages I have full SSH access to try it.

**Comment by Steve8291** [comment]
The error is because you don't have a mail server installed. I wrote the script to use postfix or some other mail utility. It calls the command `mail` and that is what is causing the error.
You could install postfix on your server and set it up so that you can receive emails with the script but it can be a bit complex to configure postfix. There are lots of guides online though.
As soon as I get some time I'll go though and change the script so there is an option to run it without a mail server. The only problem is that it will be unable to notify you of when it has updated the dns. I guess if anything stops working you will just notice that your site is down. I'll set it up to at least log things so you can check the logs if there are any problems. I've been running the script for a few years now and have never had any issues.
Just to check, do you have `curl` and `jq` installed and are you running it from a `bash` shell?

**Comment by Steve8291** [comment]
@jjuk2023 I put up a patch to allow you to run without using mail command. Didn't have time to run any tests with it but should work now. Just edit the top of the script again and add your info, then delete the default email address "root". 
Should look like `email=` or `email=''`
I'd suggest using the logfile option I made. Just make sure that path points to a directory that exists on the system where you want the logs to go to. The same goes for the cachedir path.
Please let me know how it goes.

**Comment by jjuk2023** [comment]
Thanks for the update, sadly I ended up with issues for the PATH of curl not being found (probably because it's a Debian VM). Even commenting out the pre-reqs didn't seem to help but thanks for trying, don't spend any more time on it.

**Comment by Steve8291** [comment]
Just to find out if curl is installed and where you could run:
`which curl`
`curl -V`
Might be as simple of a fix as running `sudo apt-get install curl jq`

**Comment by jjuk2023** [comment]
Yeah I have curl and jq installed so it must be something to do with the image I'm using on AWS (Bitnami Wordpress). I've found another solution now but thanks for trying to help.
